### ISSUE TITLE
Issue when formatting working .scad file: Clang failed to format source

### ISSUE THREAD

**Issue by besi** [Maxattax97/openscad-format#3]
I have a scad file that works well and generates a DXF

<img width="1100" alt="Screenshot 2020-02-05 at 10 51 53" src="https://user-images.githubusercontent.com/160412/73830785-89134800-4805-11ea-9e3b-bb696cab92c3.png">

Now when I format it using openscad-format I get the following error messages:

```
besi@BesiMac:~/Fablab/walkytalky% openscad-format --version
0.2.0
besi@BesiMac:~/Fablab/walkytalky% openscad-format -i walkytalky.scad
Error reading /var/folders/v5/d9y1qs_16nv9x5bsvjp1dv480000gn/T/tmp-15507Ig82TcU4yR95/.clang-format: Invalid argument
Failure while formatting with Clang AssertionError [ERR_ASSERTION]: Clang failed to format source
    at format (/usr/local/lib/node_modules/openscad-format/index.js:157:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async feed (/usr/local/lib/node_modules/openscad-format/index.js:195:20)
    at async /usr/local/lib/node_modules/openscad-format/index.js:287:28
    at async Promise.all (index 0)
    at async main (/usr/local/lib/node_modules/openscad-format/index.js:285:9) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: '',
  expected: true,
  operator: '=='
}
Failed to feed to formatter and write output AssertionError [ERR_ASSERTION]: Clang failed to format source
    at format (/usr/local/lib/node_modules/openscad-format/index.js:157:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async feed (/usr/local/lib/node_modules/openscad-format/index.js:195:20)
    at async /usr/local/lib/node_modules/openscad-format/index.js:287:28
    at async Promise.all (index 0)
    at async main (/usr/local/lib/node_modules/openscad-format/index.js:285:9) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: '',
  expected: true,
  operator: '=='
}
Failed to feed input files AssertionError [ERR_ASSERTION]: Clang failed to format source
    at format (/usr/local/lib/node_modules/openscad-format/index.js:157:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async feed (/usr/local/lib/node_modules/openscad-format/index.js:195:20)
    at async /usr/local/lib/node_modules/openscad-format/index.js:287:28
    at async Promise.all (index 0)
    at async main (/usr/local/lib/node_modules/openscad-format/index.js:285:9) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: '',
  expected: true,
  operator: '=='
}
besi@BesiMac:~/Fablab/walkytalky% 
```

I used openscad-format for another file where it worked well.
Also I tried to change the `if` statement to `if (DXF == true)` since the error says it expects the `==` operator. But that did not help.

**Comment by Maxattax97** [comment]
@besi Are you comfortable sharing your `walkytalky.scad` file so I can reproduce later today?

It looks like it's trying to format the file with Clang but getting nothing (empty string) out of it. It could be related to MacOS temp directories (haven't tested on Mac before), or it could be something else.

**Comment by besi** [comment]
I intended to add it and then forgot along the way. Thanks a lot for looking into this. I was looking for a way to prettify my scad file and I'm glad you made the effort to create such a tool! So thanks a bunch.

```scad
DXF = true; // set to true to see the DXF projection, for a laser cutter for example

file = "makercase-50-30-105-inside-3-5mm-thickness.dxf";
thickness = 3.5;

inner_width = 50;
inner_height = 30; 
inner_depth = 105;

outer_width = inner_width + 2 * thickness;
outer_height = inner_height + 2 * thickness;
outer_depth = inner_depth + 2 * thickness;

spacing = 6;

module dxf(layer){
        import (file =  "makercase-50-30-105-inside-3-5mm-thickness.dxf",layer = layer);
}

module back(){
        linear_extrude(height = thickness, center = true) difference(){
            dxf("back_outsideCutPath", 0); // , - outer_height - spacing
            plug_radius = 3.5;
            translate([outer_width / 2, outer_height + spacing / 2 * 2 + outer_height / 2]) circle(plug_radius, $fn = 20);
        }
}

module top(){
    radius = 16;
    circle_y_offset = 24;
    offset_x = outer_depth + outer_width + 1 * spacing;
    offset_y = 3;
        linear_extrude(height = thickness, center = true)

    difference(){
    dxf("top_outsideCutPath", 0);

    // Speaker
    translate([offset_x + (outer_width / 2), offset_y + circle_y_offset])
        circle(r = radius, $fn=50);
        
        // Holes
        distance = 29 / 2;
        translate([offset_x + (outer_width / 2) - distance, offset_y + circle_y_offset - distance]) circle(r = 1, $fn=20);
        translate([offset_x + (outer_width / 2) + distance, offset_y + circle_y_offset - distance]) circle(r = 1, $fn=20);
        translate([offset_x + (outer_width / 2) - distance, offset_y + circle_y_offset + distance]) circle(r = 1, $fn=20);
        translate([offset_x + (outer_width / 2) + distance, offset_y + circle_y_offset + distance]) circle(r = 1, $fn=20);

        // LED 
        led_radius = 2.3;
        led_offset = 7;
        translate([offset_x + (outer_width / 2), offset_y + circle_y_offset + radius + led_offset]) circle(r = led_radius, $fn=20);
        
        // Mic 
        mic_offset = led_offset + led_radius + 7;
        translate([offset_x + (outer_width / 2), offset_y + circle_y_offset + radius + mic_offset]) circle(r = .5, $fn=20);
    }
    
}
    

module front(){

    socket_width = 7.5;
    chip_height = 12;

    linear_extrude(height = thickness, center = true) difference(){
        dxf("front_outsideCutPath", 0);
        
        // Microusb
        chip_width = 17;
        chip_offset = 12.5;
        translate([outer_width - chip_width/2 - chip_offset , spacing / 2 + chip_height]) square([chip_width, 1], center = true);
        translate([outer_width - chip_width/2 - chip_offset , spacing / 2 + chip_height + 1.5]) square([socket_width, 3], center = true);
        
        // Switch
        switch_height = 25;
        switch_radius = 3;
        translate([outer_width - chip_width/2 - chip_offset , spacing / 2 + switch_height]) circle(switch_radius, $fn=50);   
        
        // Charging indicator
        charging_radius = .8;
        translate([outer_width - chip_width - chip_offset + 1 , spacing / 2 + chip_height + 4]) circle(charging_radius, $fn=20);   
    }
}

module left(){
    
    linear_extrude(height = thickness, center = true) difference(){
        dxf("left_outsideCutPath", 0);
        button_radius = 3.3;
        button_distance = 14;
        button_offset = 35;
        translate([outer_width + spacing / 2 + button_offset, spacing/2 + outer_height / 2]) circle(button_radius, $fn = 20);
        translate([outer_width + spacing / 2 + button_offset + button_distance, spacing/2 + outer_height / 2]) circle(button_radius, $fn = 20);
    }
}

module right(){
    linear_extrude(height = thickness, center = true)
        dxf("right_outsideCutPath", 0);
}

module bottom(){
    linear_extrude(height = thickness, center = true)
        dxf("bottom_outsideCutPath", 0);
}

module box(){
    front();
    back();
    right();
    left();
    bottom();
    top();
}

if (DXF){
    projection (cut=true) 
    box()   ;
}	else {
    box();
}
```

**Comment by besi** [comment]
On another note: I came across this post, where someone was looking for a formatter. I don't have an account.

http://forum.openscad.org/quot-lint-quot-like-support-for-OpenSCAD-td25712.html

**Comment by Maxattax97** [comment]
I think there may be a syntax error in your `.openscad-format` file. Can you provide that, or ensure it's not used?

**Comment by besi** [comment]
There was one, but it was empty:

    35747149 -rw-r--r--   1 besi  staff       0 Feb  4 22:23 .openscad-format

After deleting it the formatting now finally works.
Thanks for your help with this.

**Comment by Maxattax97** [comment]
I'll add a message so it's more obvious that's what's going on.

Thanks for the report.

**Comment by Maxattax97** [comment]
Changes are reflected in b49ee43b8cdcefda9216d2318bcbe16cbe037c2c or version 1.0.0 (first stable/official release).
